/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(a){if(a.__qc)return a.__qc;var k=a.document,x=a.navigator,L="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),E=!1,C=0,d=[],g=[],m=[],p={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},l=[],r={},F=0,G=[],y=null,V={},w={},ha=null,u,W=[].slice,ia,X,M,n,A,Y,N,ja,ka,la,H,Z,O,P,ma,I,na,oa,pa,qa,q,ra,B,Q,sa,$,ta,ua,aa,s,va,ba,R,S,wa,xa,T,ya,ca,da,za,ea,z,J,K,U,fa,v=function(b){try{return{init:P,hash:O,rules:wa,hasRules:T,defaults:za,__qc:function(){return!0}}[b].apply(null,W.call(arguments,1))}catch(c){return!1}};v.evts=0;v.v=2;v.SD=L;v.qpixelsent=[];S=function(b){var c=b?b.length||
0:0,e;for(e=0;e<c;e++)if(!b[e])return!1;return!0};da=function(b){(b=b||a._qacct)&&(aa(l,b)||l.push(b))};aa=function(b,c){var e=b.length,a;for(a=0;a<e;a++)if(b[a]===c)return!0;return!1};ba=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};R=function(b){var c,e;c=ba(b);if("array"===c)return b.slice(0);if("object"===c){c={};for(e in b)b.hasOwnProperty(e)&&(c[e]=b[e]);return c}return"string"===c?""+b:b};T=function(b){return aa(m,b)};za=function(b,c){var e;b&&((e=V[b])&&(c=
U(c,e)),c.qacct&&delete c.qacct,V[b]=c)};ea=function(b){var c,e;if(n(b))for(c in b)if("string"==typeof b[c]){c=b.event||"load";e=b.media||"webpage";"rule"!==c&&"load"!==c||"webpage"!==e&&"ad"!==e?q(b):(e=b.qacct||a._qacct,b.qacct=e,c=(c=w[e])?U(c,b):b,w[e]=c);da(b.qacct);break}else"object"==typeof b[c]&&null!=b[c]&&ea(b[c])};U=function(b,c){var e={};e.qacct=b.qacct||c.qacct;e.event="load"===b.event||"load"===c.event?"load":b.event&&c.event?b.event||c.event:null;e.media=null;e.media="webpage"===b.media||
"webpage"===c.media?"webpage":"ad"===b.media||"ad"===c.media?"ad":b.media||c.media;$(e,b,c);$(e,c,b);e.event||delete e.event;e.media||delete e.media;return e};$=function(b,c,e){var a,D,d,g,m,t;for(a in c)c.hasOwnProperty(a)&&!b.hasOwnProperty(a)&&(D=c[a],d=e[a],g="",m=!!D&&"string"==typeof D,t=!!d&&"string"==typeof d,m&&(g=D),m&&t&&(g+=","),t&&(g+=d),b[a]=g)};z=function(){var b=[],c,a;if(!(0<F)){va();for(c in w)w.hasOwnProperty(c)&&w[c]&&(a=w[c],b.push(a),delete w[c]);1==b.length&&q(b[0]);1<b.length&&
q(b)}};J=function(b){var c=[],a,f;for(a=0;a<b.length;a++)f=b[a],p.hasOwnProperty(f.substring(2))?r[f]=5:T(f)||c.push(f);if(0===c.length)z();else for(a=0;a<c.length;a++)f=c[a],m.push(f),ta(f)};ua=function(){for(var b;G[0]&&("loaded"==G[0].readyState||"complete"==G[0].readyState);)b=G.shift(),b.onreadystatechange=null,y.parentNode.insertBefore(b,y),K()};ta=function(b){var c,a;c=("https:"===k.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+b+".js";y=y||k.scripts[0];F++;a=k.createElement("script");
"async"in a?(a.src=c,a.async=!1,a.onload=function(){r[b]=0;K()},a.onerror=function(){r[b]=1;K()},y.parentNode.insertBefore(a,y)):a.readyState?(r[b]=2,G.push(a),a.onreadystatechange=ua,a.src=c):(r[b]=4,K())};K=function(){F-=0<F?1:0;z()};wa=function(){var b=!0,c,a,f;if(arguments.length){f=function(c){b?ea(c):q(c,!0)};for(c=0;c<arguments.length;c++)a=W.call(arguments[c],0),a.splice(1,0,f),xa.apply(null,a);b=!1;E&&z()}};xa=function(b,c){var a=[],f=[],D=c||q,d,l,p,t,ga;if((d=W.call(arguments,2))&&d.length){l=
d[0]||S;p=d[1];t=d[2];d=t.length;for(ga=0;ga<d;ga++)a.push(!1),f.push(null);a={p:b,f:a,r:l,c:t,a:p,v:f};T(b)||m.push(b);g.push(a);ya(a,D)}};ya=function(b,c){var a=b?b.c?b.c.length:0:0,f;for(f=0;f<a;f++)(function(a){var e,f;try{e=b.c[a][0],f=b.c[a].slice(1),f.splice(0,0,function(e){b.f[a]=!0;b.v[a]=e;ca(b,c)}),e.apply(null,f)}catch(d){b.f[a]=!0,b.v[a]=!1,ca(b,c)}})(f)};ca=function(b,c){var a=b.a,f=b.v,d=b.r||S,g,m,l,t,p,h;(g=S(b.f))&&(g=g&&d(f));if(g)for(f=0;f<a.length;f++)try{m=a[f][0];l=1<a[f].length?
a[f].slice(1):[];l=l.concat(b.v);t=m.apply(null,l);p={qacct:b.p,event:"rule"};for(h in t)t.hasOwnProperty(h)&&"qacct"!==h&&(p[h]=t[h]);c(p)}catch(n){}};ia=function(){return X(0)!==X(6)?1:0};X=function(b){b=new Date(2E3,b,1,0,0,0,0);var a=b.toGMTString(),a=new Date(a.substring(0,a.lastIndexOf(" ")-1));return b-a};M=function(b){return b.replace(/\./g,"%2E").replace(/,/g,"%2C")};A="function"===typeof encodeURIComponent?encodeURIComponent:M;n=function(b){return"undefined"!=typeof b&&null!=b};Y=function(){return Math.round(2147483647*
Math.random())};N=function(b){var a="",e=k.cookie,f;if(!e)return a;f=e.indexOf(b+"\x3d");b=f+b.length+1;-1<f&&(a=e.indexOf(";",b),0>a&&(a=e.length),a=e.substring(b,a));return a};ja=function(){var b="",a=H(),e,f,d;if(1===C)return";fpan\x3du;fpa\x3d";e=O(a);for(f=0;f<L.length;f++)if(L[f]===e)return";fpan\x3du;fpa\x3d";e=new Date;f=N("__qca");if(0<f.length){try{d=+f.split("-")[2],338688E5<e-d&&(k.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(d+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""))}catch(g){}b+=
";fpan\x3d0;fpa\x3d"+f}0===N("__qca").length&&(f="P0-"+Y()+"-"+e.getTime(),k.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(e.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""),f=N("__qca"),b=0<f.length?b+(";fpan\x3d1;fpa\x3d"+f):b+";fpan\x3du;fpa\x3d");return b};ka=function(b){k.cookie=b+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+H()};H=function(){var b,a,e,f;b=k.domain;"www."===b.substring(0,4)&&(b=b.substring(4,b.length));a=b.split(".");f=a.length;
if(3>f)return b;e=a[f-1];return 3>e.length?b:b=a[f-2]+"."+e};Z=function(b,a){var e;for(e=0;e<a.length;e++)b^=a.charCodeAt(e),b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24);return b};O=function(b){var a;a=Z(2166136261,b);b=Z(3386659096,b);return Math.round(Math.abs(a*b)/65536).toString(16)};Q=function(b,c,e){var f="",d=a._qacct,g=null,m="webpage",l="load",p={},k,h,d=c?c.qacct||a._qacct:a._qacct;k=w[d];c?k&&(c=U(c,k)):c=k;d&&delete w[d];if(null!=c)for(h in c)p[h]=!0,c.hasOwnProperty(h)&&"string"===typeof h&&
"string"===typeof c[h]&&("uid"===h||"uh"===h?(ma()||(g=O(c[h])),delete c[h]):"qacct"!==h&&(0<c[h].length?f+=";"+h+b+"\x3d"+A(c[h]):p[h]=!1,"media"===h&&(m=c[h]),"event"===h&&(l=c[h])));if("string"!==typeof d){if(!n(a._qacct)||0===a._qacct.length)return"";d=a._qacct}if(d&&(k=V[d]))for(h in k)"string"===typeof h&&k.hasOwnProperty(h)&&!p[h]&&(f+=";"+h+b+"\x3d"+A(k[h]),"media"===h&&(m=k[h]),"event"===h&&(l=k[h]));p=r[d];n(p)||(p=3);f+=";rf"+b+"\x3d"+p;"string"===typeof g&&(c.uh=g,f+=";uh"+b+"\x3d"+A(g));
if("webpage"===m&&"load"===l){for(c=0;c<v.qpixelsent.length;c++)if(v.qpixelsent[c]===d&&!e)return"";v.qpixelsent.push(d)}"ad"===m&&(C=1);return";a"+b+"\x3d"+d+f};sa=function(){var b=k.getElementsByTagName("meta"),a="",e,f,d,g;for(e=0;e<b.length;e++){d=b[e];if(1E3<=a.length)return a;n(d)&&n(d.attributes)&&n(d.attributes.property)&&n(d.attributes.property.value)&&n(d.content)&&(f=d.attributes.property.value,d=d.content,3<f.length&&"og:"===f.substring(0,3)&&(0<a.length&&(a+=","),g=80<d.length?80:d.length,
a+=M(f.substring(3,f.length))+"."+M(d.substring(0,g))))}return A(a)};la=function(b){return"object"===typeof b?["p","approved"===b.consent?"a":"d","asserted"===b.source?"e":"i"].join(""):""};ma=function(){var b=!1;n(a.external)&&(b=a.external,b="function"===typeof b.InPrivateFilteringEnabled&&!0===b.InPrivateFilteringEnabled());return b||"1"==x.doNotTrack||"yes"===x.doNotTrack||"1"==x.msDoNotTrack};q=function(b,c){var e="function"===typeof encodeURIComponent?"n":"s",f=Y(),g="",m="",p="",l="",t="",
r="u",h="1",s=0,u=[],q,w,y,z;C=0;n(v.qpixelsent)||(v.qpixelsent=[]);if(n(b))for(q in b)if("string"==typeof b[q]){m=Q("",b,c);break}else"object"==typeof b[q]&&null!=b[q]&&(++s,m+=Q("."+s,b[q],c));else"string"===typeof _qacct&&(m=Q("",null,c));0!==m.length&&(s=x.cookieEnabled?"1":"0","undefined"!=typeof x.javaEnabled&&(r=x.javaEnabled()?"1":"0"),n(a._qmeta)&&(p=";m\x3d"+A(a._qmeta),a._qmeta=null),self.screen&&(g=screen.width+"x"+screen.height+"x"+screen.colorDepth),w=new Date,y=ia(),z=ja(),a.location&&
a.location.href&&(l=A(a.location.href)),k&&k.referrer&&(t=A(k.referrer)),a.self===a.top&&(h="0"),q=sa(),u.push("/pixel;r\x3d"+f+m+z+";ns\x3d"+h+";ce\x3d"+s),u.push(";je\x3d"+r+";sr\x3d"+g+";enc\x3d"+e+";dst\x3d"+y+";et\x3d"+w.getTime()+";tzo\x3d"+w.getTimezoneOffset()+p+";ref\x3d"+t+";url\x3d"+l+";ogl\x3d"+q),d.push(u),B())};ra=function(b){var c=new Image;b=[a.location.protocol,"//pixel.",na(u)?"quantserve.com":"quantcount.com",b[0],";cm\x3d",la(u),b[1]].join("");c.alt="";c.src=b;c.onload=function(){c&&
"number"==typeof c.width&&3===c.width&&ka("__qca")}};B=function(){if(u)for(;d.length;)ra(d.shift());else qa()};na=function(b){return!0===b||1===b||1===b||n(b)&&"approved"===b.consent?!0:!1};qa=function(){if(!n(u)){if(a.top===a.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){oa("getConsent","advertising");return}}else if(a.postMessage&&"object"===typeof JSON){pa("getConsent","advertising");return}u=1}B()};oa=function(b,a){u=PrivacyManagerAPI.callApi(b,"quantserve.com",
H(),"truste.com",a);B()};pa=function(b,c){var e={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:b,self:"quantserve.com",domain:H(),authority:"truste.com",type:c}};if(a.addEventListener)a.addEventListener("message",I,!1);else if(a.attachEvent)a.attachEvent("onmessage",I);else{u=!0;B();return}try{a.top.postMessage(JSON.stringify(e),"*")}catch(d){}ha=setTimeout(function(){n(u)||(u=!0,B())},25)};I=function(b){var c=null;if(b.source===window.top){try{c="object"===typeof JSON&&JSON.parse(b.data)}catch(e){}c&&
"object"===typeof c.PrivacyManagerAPI&&(clearTimeout(ha),a.removeEventListener?window.removeEventListener("message",I,!1):a.detachEvent&&window.detachEvent("onmessage",I),u=c.PrivacyManagerAPI,B())}};fa=function(){var b=arguments,a,e;s([].slice.call(b));for(e=0;e<b.length;e++)a=b[e],q(a);l.length?J(l.slice(0)):z()};s=function(b){var c=ba(b);if("array"===c)for(c=0;c<b.length;c++)s(b[c]);else"object"===c&&da(b.qacct||a._qacct)};va=function(){var b;a._qevents.length||a.ezt.length||"undefined"===typeof _qacct||
q({qacct:a._qacct});if(!v.evts){for(b in a._qevents)a._qevents.hasOwnProperty(b)&&q(a._qevents[b]);for(b in a.ezt)a.ezt.hasOwnProperty(b)&&q(a.ezt[b]);a._qevents={push:fa};a.ezt.push=function(){var b=arguments,e;if(n(a.queueManager))for(e=0;e<b.length;e++)a.queueManager.push(b[e]);else fa.apply(this,arguments)};v.evts=1}};P=function(){var b;n(a._qevents)||(a._qevents=[]);n(a.ezt)||(a.ezt=[]);a._qoptions&&(b=R(a._qoptions),s(a._qoptions),a._qevents.push(b),a._qoptions=null);a.qcdata&&(b=R(a.qcdata),
s(a.qcdata),a._qevents.push(b),a.qcdata=null);a.smarttagdata&&(b=R(a.smarttagdata),s(a.smarttagdata),a._qevents.push(b),a.smarttagdata=null);v.evts||(a._qevents.push=function(){s([].slice.call(arguments));J(l.slice(0));return[].push.apply(a._qevents,arguments)},a.ezt.push=function(){s([].slice.call(arguments));J(l.slice(0));return[].push.apply(a.ezt,arguments)});s(a.ezt);s(a._qevents);s({qacct:a._qacct});a._qoptions=null;l.length?J(l.slice(0)):z();E=!0};a.quantserve=a.quantserve||P;v.quantserve=P;
return v}(window);
try{__qc("hasRules","p-vFFnErCrtYw2R")||function(a,k,x){try{__qc("defaults",a,{labels:"_fp.event.Default"})}catch(L){}var E=function(a,d,g){return a?"nc"===a?!d||!g||0>d.indexOf(g):"eq"===a?d===g:"sw"===a?0===d.indexOf(g):"ew"===a?(a=d.length-g.length,d=d.lastIndexOf(g,a),-1!==d&&d===a):"c"===a?0<=d.indexOf(g):!1:!1},C=function(a){var d=x.createElement("a");d.href=a;return d},d=function(a,d,g){var r;r=k.top===k.self?x.location.href:C(x.referrer).href;E(d,r,g)?a(r):a(!1)},g=function(a){return"array"==={}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?
{labels:a.join(",")}:{labels:""+a}};__qc("rules",[a,null,[[g,"_fp.event.Homepage"]],[[function(a,d,g){var r;r=k.top===k.self?x.location.pathname:C(x.referrer).pathname;E(d,r,g)?a(r):a(!1)},"eq","/"]]],[a,null,[[g,"_fp.event.Features"]],[[d,"eq","https://teamtreehouse.com/features"]]],[a,null,[[g,"_fp.event.Organizations"]],[[d,"eq","https://teamtreehouse.com/features/organizations"]]],[a,null,[[g,"_fp.event.Stories"]],[[d,"eq","https://teamtreehouse.com/stories"]]],[a,null,[[g,"_fp.event.Plans and Pricing"]],
[[d,"eq","https://teamtreehouse.com/subscribe/plans?trial\x3dyes\x26ref_evt\x3dnav-pricing"]]],[a,null,[[g,"_fp.event.Sign In"]],[[d,"eq","https://teamtreehouse.com/signin?return_to\x3d%2F"]]],[a,null,[[g,"_fp.event.Free Trial"]],[[d,"eq","https://teamtreehouse.com/subscribe/plans?trial\x3dyes\x26ref_evt\x3dnav-trial"]]],[a,null,[[g,"_fp.event.Learn"]],[[d,"sw","https://teamtreehouse.com/learn"]]],[a,null,[[g,"_fp.event.Library"]],[[d,"c","/library/"]]],[a,null,[[g,"_fp.event.About"]],[[d,"eq","https://teamtreehouse.com/about"]]],
[a,null,[[g,"_fp.event.About You Survey"]],[[d,"eq","https://teamtreehouse.com/about_you_survey"]]],[a,null,[[g,"_fp.event.Account"]],[[d,"eq","https://teamtreehouse.com/account"]]],[a,null,[[g,"_fp.event.Billing"]],[[d,"eq","https://teamtreehouse.com/account/billing"]]],[a,null,[[g,"_fp.event.Billing Edit"]],[[d,"eq","https://teamtreehouse.com/account/billing/edit"]]],[a,null,[[g,"_fp.event.Account Edit"]],[[d,"eq","https://teamtreehouse.com/account/edit"]]],[a,null,[[g,"_fp.event.Enrollment"]],
[[d,"eq","https://teamtreehouse.com/account/enrollment"]]],[a,null,[[g,"_fp.event.Notifications"]],[[d,"eq","https://teamtreehouse.com/account/notifications"]]],[a,null,[[g,"_fp.event.Privacy"]],[[d,"eq","https://teamtreehouse.com/account/privacy"]]],[a,null,[[g,"_fp.event.Referrals"]],[[d,"eq","https://teamtreehouse.com/account/referrals"]]],[a,null,[[g,"_fp.event.Cancel"]],[[d,"eq","https://teamtreehouse.com/account/subscription/confirm_cancel"]]],[a,null,[[g,"_fp.event.Pause"]],[[d,"eq","https://teamtreehouse.com/account/subscription/pause"]]],
[a,null,[[g,"_fp.event.Account Reactivations"]],[[d,"c","/account_reactivations"]]],[a,null,[[g,"_fp.event.Community"]],[[d,"c","/community"]]],[a,null,[[g,"_fp.event.Join"]],[[d,"sw","https://teamtreehouse.com/join"]]],[a,null,[[g,"_fp.event.Stories"]],[[d,"c","/stories/"]]],[a,null,[[g,"_fp.event.Plans"]],[[d,"sw","https://teamtreehouse.com/subscribe/plans"]]],[a,null,[[g,"_fp.event.Tracks"]],[[d,"c","/tracks/"]]],[a,null,[[g,"_fp.event.Workspaces"]],[[d,"c","/workspaces"]]],[a,null,[[g,"_fp.event.Tech Degree"]],
[[d,"sw","https://teamtreehouse.com/techdegree"]]],[a,null,[[g,"_fp.event.Subscription"]],[[d,"sw","https://teamtreehouse.com/subscribe/new"],[d,"nc","plan\x3d1412"]]],[a,null,[[g,"_fp.event.Tech Degree Form"]],[[d,"sw","https://teamtreehouse.com/subscribe/new?plan\x3d1412"]]],[a,null,[[g,"_fp.event.Sign In"]],[[d,"c","https://teamtreehouse.com/signin"]]])}("p-vFFnErCrtYw2R",window,document)}catch(nfe$$4){}quantserve();
try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$5){};